from __future__ import annotations

import copy
from typing import Any


DEMO_FIXTURE: dict[str, Any] = {
    "fixtureId": "demo-sandbox-previous",
    "startTime": 1_782_648_000,
    "startTimeIso": "2026-06-21T19:00:00+00:00",
    "competition": "Demo Previous Match",
    "competitionId": "demo",
    "participant1": "North Colony FC",
    "participant2": "South Colony FC",
}


DEMO_EVENTS: list[dict[str, Any]] = [
    {
        "fixtureId": DEMO_FIXTURE["fixtureId"],
        "seq": 1,
        "minute": 4,
        "clockSeconds": 240,
        "action": "attack_possession",
        "highlights": [],
        "participant": 1,
        "participantLabel": "North Colony FC",
        "possession": 1,
        "possessionLabel": "North Colony FC",
        "possessionType": "attack_possession",
        "score": {"participant1": 0, "participant2": 0},
        "description": "Attaque - 4' - North Colony FC",
        "details": ["Possession: North Colony FC (Attack possession)"],
    },
    {
        "fixtureId": DEMO_FIXTURE["fixtureId"],
        "seq": 2,
        "minute": 5,
        "clockSeconds": 296,
        "action": "shot",
        "highlights": [],
        "participant": 1,
        "participantLabel": "North Colony FC",
        "score": {"participant1": 0, "participant2": 0},
        "description": "Tir - 5' - North Colony FC - blocked",
        "details": ["Team: North Colony FC", "Result: Blocked"],
    },
    {
        "fixtureId": DEMO_FIXTURE["fixtureId"],
        "seq": 3,
        "minute": 8,
        "clockSeconds": 475,
        "action": "corner",
        "highlights": ["corner"],
        "participant": 2,
        "participantLabel": "South Colony FC",
        "possession": 2,
        "possessionLabel": "South Colony FC",
        "score": {"participant1": 0, "participant2": 0},
        "description": "Corner - 8' - South Colony FC",
        "details": ["Team: South Colony FC"],
    },
    {
        "fixtureId": DEMO_FIXTURE["fixtureId"],
        "seq": 4,
        "minute": 9,
        "clockSeconds": 520,
        "action": "high_danger_possession",
        "highlights": [],
        "participant": 2,
        "participantLabel": "South Colony FC",
        "possession": 2,
        "possessionLabel": "South Colony FC",
        "possessionType": "high_danger_possession",
        "score": {"participant1": 0, "participant2": 0},
        "description": "High danger possession - 9' - South Colony FC",
        "details": ["Possession: South Colony FC (High danger possession)"],
    },
    {
        "fixtureId": DEMO_FIXTURE["fixtureId"],
        "seq": 5,
        "minute": 10,
        "clockSeconds": 570,
        "action": "goal",
        "highlights": ["goal"],
        "participant": 2,
        "participantLabel": "South Colony FC",
        "confirmed": True,
        "score": {"participant1": 0, "participant2": 1},
        "description": "Goal - 10' - South Colony FC - confirmed",
        "details": ["Team: South Colony FC", "Confirmed"],
    },
    {
        "fixtureId": DEMO_FIXTURE["fixtureId"],
        "seq": 6,
        "minute": 18,
        "clockSeconds": 1058,
        "action": "free_kick",
        "highlights": ["free_kick"],
        "participant": 1,
        "participantLabel": "North Colony FC",
        "possession": 1,
        "possessionLabel": "North Colony FC",
        "freeKickType": "Direct",
        "score": {"participant1": 0, "participant2": 1},
        "description": "Free kick - 18' - North Colony FC - direct",
        "details": ["Team: North Colony FC", "Free kick: Direct"],
    },
    {
        "fixtureId": DEMO_FIXTURE["fixtureId"],
        "seq": 7,
        "minute": 19,
        "clockSeconds": 1095,
        "action": "shot",
        "highlights": [],
        "participant": 1,
        "participantLabel": "North Colony FC",
        "score": {"participant1": 0, "participant2": 1},
        "description": "Tir - 19' - North Colony FC - saved",
        "details": ["Team: North Colony FC", "Result: Saved"],
    },
    {
        "fixtureId": DEMO_FIXTURE["fixtureId"],
        "seq": 8,
        "minute": 27,
        "clockSeconds": 1600,
        "action": "penalty",
        "highlights": ["penalty"],
        "participant": 1,
        "participantLabel": "North Colony FC",
        "possession": 1,
        "possessionLabel": "North Colony FC",
        "confirmed": False,
        "score": {"participant1": 0, "participant2": 1},
        "description": "Penalty - 27' - North Colony FC - not confirmed",
        "details": ["Team: North Colony FC", "Pending confirmation"],
    },
    {
        "fixtureId": DEMO_FIXTURE["fixtureId"],
        "seq": 9,
        "minute": 28,
        "clockSeconds": 1640,
        "action": "var",
        "highlights": ["var"],
        "participant": 1,
        "participantLabel": "North Colony FC",
        "confirmed": True,
        "score": {"participant1": 0, "participant2": 1},
        "description": "VAR - 28' - penalty confirme",
        "details": ["Team: North Colony FC", "VAR=yes", "Confirmed"],
    },
    {
        "fixtureId": DEMO_FIXTURE["fixtureId"],
        "seq": 10,
        "minute": 29,
        "clockSeconds": 1702,
        "action": "goal",
        "highlights": ["goal"],
        "participant": 1,
        "participantLabel": "North Colony FC",
        "confirmed": True,
        "player": {"name": "Scout Ten", "rosterNumber": "10"},
        "score": {"participant1": 1, "participant2": 1},
        "description": "Goal - 29' - North Colony FC - #10 Scout Ten - confirmed",
        "details": ["Team: North Colony FC", "Player: #10 Scout Ten", "Confirmed"],
    },
    {
        "fixtureId": DEMO_FIXTURE["fixtureId"],
        "seq": 11,
        "minute": 41,
        "clockSeconds": 2430,
        "action": "red_card",
        "highlights": ["red_card"],
        "participant": 2,
        "participantLabel": "South Colony FC",
        "confirmed": True,
        "score": {"participant1": 1, "participant2": 1},
        "description": "Red card - 41' - South Colony FC - confirmed",
        "details": ["Team: South Colony FC", "Confirmed"],
    },
    {
        "fixtureId": DEMO_FIXTURE["fixtureId"],
        "seq": 12,
        "minute": 54,
        "clockSeconds": 3230,
        "action": "high_danger_possession",
        "highlights": [],
        "participant": 1,
        "participantLabel": "North Colony FC",
        "possession": 1,
        "possessionLabel": "North Colony FC",
        "possessionType": "high_danger_possession",
        "score": {"participant1": 1, "participant2": 1},
        "description": "High danger possession - 54' - North Colony FC",
        "details": ["Possession: North Colony FC (High danger possession)"],
    },
    {
        "fixtureId": DEMO_FIXTURE["fixtureId"],
        "seq": 13,
        "minute": 55,
        "clockSeconds": 3275,
        "action": "corner",
        "highlights": ["corner"],
        "participant": 1,
        "participantLabel": "North Colony FC",
        "possession": 1,
        "possessionLabel": "North Colony FC",
        "score": {"participant1": 1, "participant2": 1},
        "description": "Corner - 55' - North Colony FC",
        "details": ["Team: North Colony FC"],
    },
    {
        "fixtureId": DEMO_FIXTURE["fixtureId"],
        "seq": 14,
        "minute": 56,
        "clockSeconds": 3335,
        "action": "goal",
        "highlights": ["goal"],
        "participant": 1,
        "participantLabel": "North Colony FC",
        "confirmed": True,
        "score": {"participant1": 2, "participant2": 1},
        "description": "Goal - 56' - North Colony FC - confirmed",
        "details": ["Team: North Colony FC", "Confirmed"],
    },
    {
        "fixtureId": DEMO_FIXTURE["fixtureId"],
        "seq": 15,
        "minute": 78,
        "clockSeconds": 4660,
        "action": "penalty",
        "highlights": ["penalty"],
        "participant": 2,
        "participantLabel": "South Colony FC",
        "possession": 2,
        "possessionLabel": "South Colony FC",
        "confirmed": True,
        "player": {"name": "Striker Nine", "rosterNumber": "9"},
        "score": {"participant1": 2, "participant2": 1},
        "description": "Penalty - 78' - South Colony FC - #9 Striker Nine - confirmed",
        "details": ["Team: South Colony FC", "Player: #9 Striker Nine", "Confirmed"],
    },
    {
        "fixtureId": DEMO_FIXTURE["fixtureId"],
        "seq": 16,
        "minute": 79,
        "clockSeconds": 4722,
        "action": "shot",
        "highlights": [],
        "participant": 2,
        "participantLabel": "South Colony FC",
        "confirmed": True,
        "score": {"participant1": 2, "participant2": 1},
        "description": "Penalty missed - 79' - South Colony FC - saved",
        "details": ["Team: South Colony FC", "Result: Saved", "Confirmed"],
    },
]


def demo_fixtures() -> list[dict[str, Any]]:
    return [copy.deepcopy(DEMO_FIXTURE)]


def demo_events(fixture_id: Any | None = None) -> list[dict[str, Any]]:
    if fixture_id is not None and str(fixture_id) != str(DEMO_FIXTURE["fixtureId"]):
        return []
    return copy.deepcopy(DEMO_EVENTS)
